import 'dart:io';
// ignore_for_file: prefer_const_constructors
import 'package:flutter/material.dart';
import 'package:sampleproject/SecureStorage.dart';
import 'package:sampleproject/main.dart';
import 'package:sampleproject/model/DeployedForm.dart';
import 'package:sampleproject/sidebar.dart';
import 'package:web3dart/contracts.dart';

import 'form_tile.dart';
import 'FormBuilder.dart';

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'model/FormDetails.dart';
import 'model/ProcessStep.dart';
import 'package:simple_json_form/simple_json_form.dart';
import 'package:multi_select_flutter/multi_select_flutter.dart';
import 'dart:convert';

import 'package:sampleproject/model/UserCredentials.dart';

import 'package:json_dynamic_form/JsonDynamicForm.dart';
import 'package:json_dynamic_form/models/Autogenerated.dart';
import 'package:json_dynamic_form/models/Values.dart';

class MainPageTile extends StatefulWidget {
  MainPageTile({Key? key, required this.itemNo, this.homePage})
      : super(key: key);
  final int itemNo;
  MyHomePage? homePage;
  MainPageTile.withitemNo(final this.itemNo, this.homePage);

  @override
  State<MainPageTile> createState() => _MainPageTileState(itemNo, homePage);
}

class _MainPageTileState extends State<MainPageTile> {
  final storage = new SecureStorage(FlutterSecureStorage());
  List<String> usercreds_string = [];
  List<String> deployedForms_string = [];
  List<DeployedForm?>? PendingForms = [];
  List<String?>? CheckStep = [];
  //List<DeployedForm?>? InputForms = [];

  List<DeployedForm> deployedForms = [];
  UserCredentials? currentuser;

  _MainPageTileState(this.itemNo, this.homePage);
  MyHomePage? homePage;
  final int itemNo;
  int? currentDeployedFormIndex;
  int? currentStepIndex;

  late JsonDynamicForm jsonDynamicForm;
  List<Widget>? fields = List<Widget>.empty(growable: true);

  @override
  void initState() {
    DoStuff();

    super.initState();
  }

  Future DoStuff() async {
    await CurrentUser();
    await GetDeployedForms();
    await CheckPending();

    var formData =
        jsonDecode(PendingForms![itemNo]!.formDetails!.formJSON ?? "");

    jsonDynamicForm = JsonDynamicForm(data: formData, setState: setState);

    fields = jsonDynamicForm.generateFields();
  }

  Future CurrentUser() async {
    String? usercreds = await storage.read(key: 'currentUser');

    currentuser = UserCredentials.fromJson(jsonDecode(usercreds ?? ""));
  }

  Future GetDeployedForms() async {
    deployedForms = [];
    //Populate form builder texts list
    String? jsonString = await storage.read(key: 'deployedForms');
    setState(() {
      deployedForms_string =
          (jsonDecode(jsonString ?? "") as List<dynamic>).cast<String>();
    });

    for (String s in deployedForms_string) {
      Map<String, dynamic> data = jsonDecode(s);

      deployedForms.add(DeployedForm.fromJson(data));
    }
    //print(deployedForms_string);
    //print(deployedForms);
  }

  Future CheckPending() async {
    for (int i = 0; i < deployedForms.length; i++) {
      // print('${deployedForms[i].formDetails!.processSteps![i].stepPerformers}');
      for (int j = 0;
          j < deployedForms[i].formDetails!.processSteps!.length;
          j++) {
        if (deployedForms[i]
                .formDetails!
                .processSteps![j]
                .stepPerformers!
                .contains(currentuser!.userName) &&
            deployedForms[i].formDetails!.processSteps![j].stepCompleted ==
                false) {
          //print('Namskara Gandu');
          // if (deployedForms[i].formDetails!.processSteps![j].stepType! ==
          //         'Input Step' ||
          //     deployedForms[i].formDetails!.processSteps![j].stepType! ==
          //         'Approval Step') {
          //print('Lowde');
          currentDeployedFormIndex = i;
          currentStepIndex = j;
          // print(currentStepIndex);
          PendingForms!.add(deployedForms[i]);
          CheckStep!
              .add(deployedForms[i].formDetails!.processSteps![j].stepType);
          break;
          // }
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // fields = jsonDynamicForm.generateFields(firstTime: false);

    var screenwidth = MediaQuery.of(context).size.width;
    var screenheight = MediaQuery.of(context).size.height;
    return Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(5),
          color: Colors.blue,
        ),
        width: screenwidth / 10,
        height: screenheight / 3,
        margin: const EdgeInsets.fromLTRB(35, 20, 20, 10),
        child: Column(children: [
          Column(
            children: [
              Column(
                children: [
                  Container(
                    child: Padding(
                      padding: const EdgeInsets.all(15.0),
                      child: Text(
                        '${PendingForms![itemNo]!.formDetails?.formName}',

                        // Add Form Details
                        style: TextStyle(
                            fontSize: 22,
                            fontWeight: FontWeight.w600,
                            color: Color.fromARGB(185, 0, 0, 0),
                            decoration: TextDecoration.underline),
                      ),
                    ),
                  ),
                  if (deployedForms[currentDeployedFormIndex ?? 0]
                          .formDetails!
                          .processSteps![currentStepIndex ?? 0]
                          .stepType ==
                      'Approval Step')
                    MaterialButton(
                      color: Colors.red,
                      onPressed: () async {
                        deployedForms[currentDeployedFormIndex ?? 0]
                            .formDetails!
                            .processSteps![currentStepIndex ?? 0]
                            .inputRecorded = "Approval Step : Approved";

                        // print(jsonEncode(jsonDynamicForm.printData()));

                        deployedForms[currentDeployedFormIndex ?? 0]
                            .formDetails!
                            .processSteps![currentStepIndex ?? 0]
                            .stepCompleted = true;

                        if (currentStepIndex ==
                            deployedForms[currentDeployedFormIndex ?? 0]
                                    .formDetails!
                                    .processSteps!
                                    .length -
                                1) {
                          deployedForms[currentDeployedFormIndex ?? 0]
                              .formStatus = true;
                        }

                        deployedForms_string[currentDeployedFormIndex ?? 0] =
                            jsonEncode(
                                deployedForms[currentDeployedFormIndex ?? 0]
                                    .toJson());

                        await storage.write(
                            key: 'deployedForms',
                            value: jsonEncode(deployedForms_string));

                        await DoStuff();

                        homePage!.DoStuff();
                      },
                      child: const Text(
                        'Approve',
                        style: TextStyle(
                          color: Colors.black,
                        ),
                      ),
                    ),
                  if (deployedForms[currentDeployedFormIndex ?? 0]
                          .formDetails!
                          .processSteps![currentStepIndex ?? 0]
                          .stepType ==
                      'Input Step')
                    Padding(
                      padding: const EdgeInsets.all(12.0),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: [
                          MaterialButton(
                            color: Colors.red,
                            onPressed: () {
                              OpenForm(PendingForms![itemNo]!.formDetails!);
                            },
                            child: const Text(
                              'Input',
                              style: TextStyle(
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                ],
              ),
            ],
          ),
          // Expanded(
          //   child: ListTile(
          //     tileColor: Colors.blue,
          //     onTap: () {},
          //     hoverColor: Colors.orange,
          //   ),
          // ),
        ]));
  }

  OpenForm(FormDetails formDetails) {
    showDialog(
        context: context,
        builder: (context) => StatefulBuilder(builder: (context, setState) {
              print(jsonDecode(formDetails.formJSON ?? ""));
              return Dialog(
                child: Scaffold(
                  appBar: AppBar(
                    title: Text(formDetails.formName ?? "No Name"),
                  ),
                  body: SingleChildScrollView(
                    child: Column(
                      children: [
                        Column(children: fields!
                            // SimpleJsonForm(
                            //   jsonSchema: JsonSchema.fromJson(
                            //       jsonDecode(formDetails.formJSON ?? "")),
                            //   title: formDetails.formName,
                            //   titleStyle: const TextStyle(
                            //     fontWeight: FontWeight.bold,
                            //     fontSize: 15,
                            //   ),
                            //   description: "Fill the form carefully!",
                            //   crossAxisAlignment: CrossAxisAlignment.center,
                            //   index: 0,
                            //   imageUrl: '',
                            //   defaultValues: DefaultValues().copyWith(
                            //     nextButtonText: 'Next',
                            //     // hintDropdownText: 'Elija una opcion',
                            //     previousButtonText: 'Previous',
                            //     submitButtonText: 'Submit',
                            //     // validationDescription: 'Algunos campos requeridos faltan',
                            //     validationTitle: 'Wrong Wrong Wrong...',
                            //     fieldRequired: 'Give some value',
                            //   ),
                            //   descriptionStyleText: const TextStyle(
                            //     color: Colors.lightBlue,
                            //   ),
                            //   titleStyleText: const TextStyle(
                            //     fontWeight: FontWeight.bold,
                            //     fontSize: 16,
                            //     color: Colors.blue,
                            //   ),
                            //   onSubmit: (val) {
                            //     if (val == null) {
                            //       //print("no data");
                            //     } else {
                            //       var json = jsonEncode(val.toJson());
                            //       //print(json);
                            //     }
                            //   },
                            // ),
                            ),
                        TextButton(
                            onPressed: () async {
                              // List<DeployedForm> depForms = [];
                              // for (String s in deployedForms_string) {
                              //   Map<String, dynamic> data = jsonDecode(s);
                              //   depForms.add(DeployedForm.fromJson(data));
                              // }

                              deployedForms[currentDeployedFormIndex ?? 0]
                                      .formDetails!
                                      .processSteps![currentStepIndex ?? 0]
                                      .inputRecorded =
                                  "Input Step : " +
                                      jsonEncode(jsonDynamicForm.printData());

                              print(jsonEncode(jsonDynamicForm.printData()));

                              deployedForms[currentDeployedFormIndex ?? 0]
                                  .formDetails!
                                  .processSteps![currentStepIndex ?? 0]
                                  .stepCompleted = true;

                              if (currentStepIndex ==
                                  deployedForms[currentDeployedFormIndex ?? 0]
                                          .formDetails!
                                          .processSteps!
                                          .length -
                                      1) {
                                deployedForms[currentDeployedFormIndex ?? 0]
                                    .formStatus = true;
                              }

                              deployedForms_string[
                                  currentDeployedFormIndex ??
                                      0] = jsonEncode(
                                  deployedForms[currentDeployedFormIndex ?? 0]
                                      .toJson());

                              await storage.write(
                                  key: 'deployedForms',
                                  value: jsonEncode(deployedForms_string));

                              await DoStuff();
                              homePage!.DoStuff();

                              setState(() {});
                              Navigator.pop(context);
                            },
                            child: Padding(
                              padding: const EdgeInsets.all(10),
                              child: Text("Submit"),
                            ))
                      ],
                    ),
                  ),
                ),
              );
            }));
  }
}
